"""rename department

Revision ID: edb7b2e45d21
Revises: 779e8fa1eaaa
Create Date: 2026-01-16 14:52:22.472505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb7b2e45d21'
down_revision = '779e8fa1eaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
